import boto3
import os
import json
import urllib.parse

# ==============================
# Environment Variables
# ==============================
REGION = os.environ.get("REGION", "ap-south-1")
SNS_ARN = os.environ.get("SNS_ARN")
MAX_LABELS = int(os.environ.get("MAX_LABELS", 5))
MIN_CONFIDENCE = int(os.environ.get("MIN_CONFIDENCE", 80))

# ==============================
# AWS Clients
# ==============================
rekognition = boto3.client("rekognition", region_name=REGION)
sns = boto3.client("sns", region_name=REGION)

# Supported image formats
ALLOWED_EXTENSIONS = (".jpg", ".jpeg", ".png", ".webp")


def lambda_handler(event, context):
    try:
        # Validate S3 Event
        if "Records" not in event:
            return {
                "statusCode": 400,
                "body": json.dumps("No S3 event detected.")
            }

        record = event["Records"][0]
        bucket = record["s3"]["bucket"]["name"]
        key = urllib.parse.unquote_plus(record["s3"]["object"]["key"])

        print(f"Processing image: {key} from bucket: {bucket}")

        # Validate file type
        if not key.lower().endswith(ALLOWED_EXTENSIONS):
            print("Unsupported file type.")
            return {
                "statusCode": 400,
                "body": json.dumps("Unsupported image format.")
            }

        # ==============================
        # Rekognition: Detect Labels
        # ==============================
        response = rekognition.detect_labels(
            Image={"S3Object": {"Bucket": bucket, "Name": key}},
            MaxLabels=MAX_LABELS,
            MinConfidence=MIN_CONFIDENCE
        )

        # Extract labels with confidence
        labels = response.get("Labels", [])

        if not labels:
            labels_text = "No significant objects detected."
        else:
            labels_text = "\n".join(
                [f"• {label['Name']} ({round(label['Confidence'], 2)}%)"
                 for label in labels]
            )

        # Generate Image URL
        image_url = f"https://{bucket}.s3.{REGION}.amazonaws.com/{key}"

        # ==============================
        # Professional Email Message
        # ==============================
        message = f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🖼️  AI IMAGE ANALYSIS REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📂 Image Name:
{key}

📊 Detected Objects:
{labels_text}

🌐 View Image:
{image_url}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by AWS Rekognition
Region: {REGION}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

        print("Publishing message to SNS...")

        # Publish to SNS
        sns.publish(
            TopicArn=SNS_ARN,
            Message=message,
            Subject="AI Image Analysis Report"
        )

        print("SNS notification sent successfully.")

        return {
            "statusCode": 200,
            "body": json.dumps("Image processed successfully.")
        }

    except Exception as e:
        print(f"Error: {str(e)}")
        return {
            "statusCode": 500,
            "body": json.dumps(f"Error processing image: {str(e)}")
        }
